name = "CountFlops"
uuid = "1db9610d-79e1-487a-8d40-77f3295c7593"
authors = ["Charles Kawczynski <kawczynski.charles@gmail.com>"]
version = "0.1.0"

[deps]
Cassette = "7057c7e9-c182-5462-911a-8362d720325c"

[compat]
Cassette = "^0.2.3, 0.3.2"
julia = "^1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
